export function createAppShell(){
 const el=document.createElement('div');el.className='casino-shell';
 el.innerHTML=`<header class="topbar"><div class="brand"><span class="brand-seal">BL</span><div><small>BEARD LAWS CASINO 2.0</small><strong>PROJECT GOLD BEARD</strong></div></div><div class="balances"><div><small>BEARD LAWS BANK</small><strong data-bank>$0.00</strong></div><div><small>CASINO WALLET</small><strong data-wallet>$0.00</strong></div></div></header>
 <main class="floor"><aside class="left-rail"><button class="nav active">BEARD BANK</button><button class="nav" data-ledger-toggle>VAULTMASTER'S LEDGER</button><div class="integrity-card"><strong>HONEST BY DESIGN</strong><p>Independent outcomes. Fictional credits only.</p></div></aside>
 <section class="cabinet"><div class="marquee"><small>VAULTMASTER VERNON PRESENTS</small><h1>BEARD BANK</h1><p>BEARD ENGINE 2.0.1 • DIRECT PAGES BUILD</p></div><div class="living-vault"><div class="vault-icon">✦</div><div><span>THE LIVING VAULT</span><strong data-charges>0 / 30 CHARGES</strong><div class="charge-track"><div data-charge-fill></div></div></div></div><div class="message" data-message>ENGINE READY</div><div class="reel-host" data-reel-host></div><div class="control-deck"><div class="meter"><small>SPINS</small><strong data-spins>0</strong></div><div class="meter"><small>SESSION RTP</small><strong data-rtp>0.00%</strong></div><button class="spin-button" data-spin>SPIN</button></div></section>
 <aside class="right-rail"><div class="stats-card"><small>LIVE SESSION</small><div><span>WAGERED</span><strong data-wagered>$0.00</strong></div><div><span>RETURNED</span><strong data-returned>$0.00</strong></div></div></aside></main>
 <aside class="ledger" data-ledger><button class="ledger-close" data-ledger-toggle>×</button><small>VAULTMASTER VERNON'S</small><h2>LEDGER</h2><section><h3>GAME INTEGRITY</h3><p>RNG: <code>crypto.getRandomValues()</code></p><p>Mode: 243 Ways</p><p class="warning">94.20% is a legacy target, not a verified v2 RTP.</p></section></aside>
 <footer>Free fictional entertainment simulator. Nothing can be purchased, withdrawn, transferred, or redeemed.</footer>`;
 return el;
}